name: Kodekvalitet

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: 21

jobs:
  codeql-analyze:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yaml

  dependency-submission:
    permissions:
      contents: write
    uses: ./.github/workflows/dependency-submission.yaml
