name: Kodekvalitet

on:
  workflow_call:
    inputs:
      codeql:
        required: false
        type: boolean
        default: true
      java-version:
        required: false
        type: string
        default: 21

jobs:
  codeql-analyze:
    if: ${{ inputs.codeql }}
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yaml
    with:
      java-version: ${{ inputs.java-version }}

  dependency-submission:
    permissions:
      contents: write
    uses: ./.github/workflows/dependency-submission.yaml
    with:
      java-version: ${{ inputs.java-version }}
