name: Kodekvalitet

on:
  workflow_call:

jobs:
  codeql-analyze:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yaml

  detekt-scan:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/detekt.yaml

  dependency-submission:
    permissions:
      contents: write
    uses: ./.github/workflows/dependency-submission.yaml
