name: Publiser JAR

on:
  workflow_call:

jobs:
  publish-jar:
    name: Publiser JAR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Valider Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Sett opp Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Sett opp Gradle
        uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew publish --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
